- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf: #dnf denotes redhat os otherwise apt denotes ubuntu and yum denotes linux
    name: nginx
      state: latest
  - name: starting nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes